### ISSUE TITLE
Hello, some questions about CartoonGAN

### ISSUE THREAD

**Issue by longxiong2016** [SystemErrorWang/CartoonGAN#1]
Hi, I'm also reproducing Cartoongan, but I can't get smooth effect, just some change of color. can you get it? How about your result? I did it according to the point of the paper.

**Comment by longxiong2016** [comment]
I use it for change of scenery

**Comment by SystemErrorWang** [comment]
@longxiong2016 I added some results images, please check them. I may have got better results than yours but still far from satisfaction I think.

**Comment by longxiong2016** [comment]
Thank you very much, you mention: patch size for discriminator is 28(70 in original paper),what the patch size means?

**Comment by SystemErrorWang** [comment]
@longxiong2016 
CartoonGan used patch discriminator, random cropped 256*256 image to 70*70 size and then fed into the discriminator.

**Comment by longxiong2016** [comment]
Aha, the paper said " instead of a regular full-image discriminator, we use a simple patch-level discriminator with fewer parameters in D. ", but I really can't fine the 7070 size in the paper specifically.

**Comment by SystemErrorWang** [comment]
@longxiong2016 
Well maybe I just confused this paper with cyclegan? In cyclegan they also used patch discriminator and the patch size is 70*70, and the total size in this paper and cyclegan are the same, 256*256.

**Comment by longxiong2016** [comment]
Could you tell me your email, we can discuss easily?HaHa

**Comment by SystemErrorWang** [comment]
Sure, you can contact me through secret_wang@outlook.com
