### ISSUE TITLE
How can i get 1280*720 cartoonganed image using your code?

### ISSUE THREAD

**Issue by yustephano1970** [SystemErrorWang/CartoonGAN#6]
Hi SystemErrorWang ~~
First of all, thanks for sharing your valuable code & result with github.
I tried my sample image 1270*720 and I get 256 * 256 sized image as your code says.
But, your new result image is not 256 * 256 maybe. how can get large image like your new result?

thanks

**Comment by SystemErrorWang** [comment]
it seems that with tflite, you need to resize the image to 256*256 first
i will upload another version that support random input size later

**Comment by SystemErrorWang** [comment]
@yustephano1970 updated new script and model weight, random input size is supported now

**Comment by yustephano1970** [comment]
thank you for your help. i will try....
