### ISSUE TITLE
I'm waiting your paper....

### ISSUE THREAD

**Issue by yustephano1970** [SystemErrorWang/CartoonGAN#7]
first...i'm sorry my late reply for your help about the free size cartoonize...
it worked fine and got original image size cartoonized product...thanks...

cartoongan is very interesting........and your result is the finest image ever i saw in cartoongan applied. 

i'm waiting your paper.....post up here your paper...thanks in advance

**Comment by SystemErrorWang** [comment]
@yustephano1970 our work is accepted to  CVPR2020, code and other materials will be open-sourced soon

**Comment by yustephano1970** [comment]
congratulations!!!!! 
I'm happy to hear that news...
I hope there is something good going on in the future.
congratulations!!!
